FROM --platform=$BUILDPLATFORM golang:1.21@sha256:24a09375a6216764a3eda6a25490a88ac178b5fcb9511d59d0da5ebf9e496474 as build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM alpine:3.18@sha256:eece025e432126ce23f223450a0326fbebde39cdf496a85d8c016293fc851978

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="wp-s3-action"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/wp-s3-action"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/wp-s3-action"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/wp-s3-action"

COPY --from=build /src/dist/wp-s3-action /bin/wp-s3-action
ENTRYPOINT ["/bin/wp-s3-action"]
